package com.github.dimitryivaniuta.fraud.domain;

/**
 * Origin of the feature snapshot used to produce a decision.
 */
public enum FeatureSource {
    /** Features were loaded from Redis. */
    REDIS,

    /** Features were loaded from the durable feature table. */
    POSTGRES,

    /** Features were deterministic fallback values because no external data was available. */
    FALLBACK,

    /** Features were generated by the asynchronous enrichment pipeline. */
    ENRICHED
}
